# Generated by Django 5.1.7 on 2025-04-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
