# Generated by Django 5.1.7 on 2025-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
