# Generated by Django 5.1.7 on 2025-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.CharField(blank=True, choices=[('no-category', 'No Category'), ('food', 'Food'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], default='no-category', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='categories',
            field=models.CharField(blank=True, choices=[('no-category', 'No Category'), ('salary', 'Salary'), ('investment', 'Investment'), ('gift', 'Gift'), ('other', 'Other'), ('business', 'Business'), ('rental-income', 'Rental Income'), ('interest-income', 'Interest Income'), ('dividends', 'Dividends')], default='no-category', max_length=20, null=True),
        ),
    ]
