# Generated by Django 5.1.7 on 2025-03-27 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('activity', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, choices=[('transit', 'Transit'), ('visit', 'Visit'), ('food', 'Food'), ('accommodation', 'Accommodation')], max_length=20)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='travel.travel')),
            ],
        ),
    ]
