# Generated by Django 5.1.7 on 2025-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='tag',
            field=models.CharField(blank=True, choices=[('transit', 'Transit'), ('visit', 'Visit'), ('food', 'Food'), ('accommodation', 'Accommodation'), ('other', 'Other'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('shopping', 'Shopping'), ('leisure', 'Leisure'), ('sports', 'Sports')], max_length=20, null=True),
        ),
    ]
