# Generated by Django 5.1.7 on 2025-04-12 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_itinerary_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_travels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='tag',
            field=models.CharField(blank=True, choices=[('transit', 'Transit'), ('visit', 'Visit'), ('food', 'Food'), ('accommodation', 'Accommodation'), ('other', 'Other'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('shopping', 'Shopping'), ('leisure', 'Leisure'), ('sports', 'Sports')], default=None, max_length=20, null=True),
        ),
    ]
