# Generated by Django 5.1.7 on 2025-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_collaborators_alter_itinerary_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
