# Generated by Django 5.1.7 on 2025-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_itinerary_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
