# Generated by Django 5.1.7 on 2025-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_itinerary_latitude_itinerary_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
