# Generated by Django 5.1.7 on 2025-04-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_itinerary_map_url_alter_itinerary_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='longitude',
            new_name='location_lon',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='map_url',
            new_name='location_url',
        ),
    ]
