# Generated by Django 5.1.7 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_travel_destination_alter_itinerary_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
