# Generated by Django 5.1.7 on 2025-04-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_rename_date_itinerary_start_date_itinerary_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='user',
            new_name='owner',
        ),
    ]
