# Generated by Django 5.1.7 on 2025-04-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_rename_user_travel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='owner',
            new_name='user',
        ),
    ]
